development:
  adapter: postgresql
  encoding: utf8
  database: plentry_dev
  pool: 5
  username: username
  password: pass
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: plentry_test
  pool: 5
  username: username
  password: pass
  host: localhost
